CREATE TABLE IF NOT EXISTS estates (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  phase INT NOT NULL,
  block VARCHAR(20) NOT NULL,
  floor INT NOT NULL,
  area INT DEFAULT 0 NOT NULL,
  rooms INT DEFAULT 1 NOT NULL,
  features VARCHAR(255),
  notes VARCHAR(255),
  phone_number VARCHAR(20) NOT NULL,
  price INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
)